// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuvoohdiwdwfcsilccog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1dm9vaGRpd2R3ZmNzaWxjY29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjE4OTEsImV4cCI6MjA2NTM5Nzg5MX0.DcgSRSYGd94p477_NINb2w6sTPkvVB78PrumWY8Xufc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);